FROM node:18.13.0-alpine AS build-stage


WORKDIR /app


COPY package*.json ./


RUN npm install


COPY . .


RUN npm run build


FROM nginx:1.21.0-alpine


# Copy the React app build files to the container
COPY --from=build-stage /app/dist /usr/share/nginx/html


CMD [ "nginx", "-g", "daemon off;" ]

