services:

  client: 
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - /usr/nginx/nginx.data/dist:/usr/share/nginx/html
      - /usr/nginx/nginx.conf/nginx.conf:/etc/nginx/conf.d/default.conf




  api: 
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=developer
      - API_HOST=localhost
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_USERNAME=root
      - TYPEORM_PASSWORD=root321
      - TYPEORM_DATABASE=my_db
      - TYPEORM_PORT=5432
      - TYPEORM_HOST=postgres
    volumes:
      - ./api/user/src/app

  postgres_db:
      image: postgres:14-alpine
      ports:
        - "5432:5432"
      restart: always
      environment:
        - POSTGRES_PASSWORD=root321
        - POSTGRES_USER=root
        - POSTGRES_DB=my_db
      volumes:
        - /var/lib/pgdata:/var/lib/postgresql/data
        